name: Build and Push Using Shared Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push:
    if: github.event_name != 'pull_request'

    strategy:
      matrix:
        version:
          - 'latest'

    uses: nstwf-docker/docker-ci/.github/workflows/docker-build-push.yaml@main
    with:
      image_version: ${{ matrix.version }}
      dockerhub_image: nstwf/${{ github.event.repository.name }}
      ghcr_image: ghcr.io/${{ github.repository }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  build-push-pr:
    if: github.event_name == 'pull_request'

    permissions:
      pull-requests: write

    strategy:
      matrix:
        version:
          - 'test'

    uses: nstwf-docker/docker-ci/.github/workflows/docker-build-push-pr.yaml@main
    with:
      image_version: ${{ matrix.version }}
      dockerhub_image: nstwf/${{ github.event.repository.name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}